// A compact QR Code encoder: byte mode, error correction level L, versions 1-6 (docs/SPEC.md section 8.3).
//
// Exists so the lobby can show a scannable invite link and `npm run share` can print one in the terminal, without
// a dependency. Isomorphic (plain arrays, no globals): it runs unchanged in Node and in every browser.
//
//   qrMatrix('https://example.com/r/KQXZ')  ->  boolean[row][col]  (true = dark module, no quiet zone)
//   qrMatrix(veryLongText)                  ->  null              (does not fit version 6-L: the caller hides the QR)
//
// Deviation from the spec text: it says "versions 1-6 = up to 106 bytes", but 106 bytes is where version 5-L ends;
// version 6-L holds 134 bytes. Versions 1-6 are all supported, so the real limit is QR_MAX_BYTES = 134 (an invite
// link is about 50 bytes, so either reading has plenty of room).
//
// Why versions 1-6 only: they need no version-information blocks and have at most one alignment pattern, which keeps
// this file small. Level L is the only level implemented because the invite is shown on a screen or in a terminal,
// where damage and dirt are not a concern and a smaller code scans faster.
//
// Verified against an independent decoder (jsQR) over every version, see specs/unit/qr.spec.js for what is kept in the repo.

/** Largest payload, in UTF-8 bytes, that fits version 6-L. */
export const QR_MAX_BYTES = 134;

// ---- Version tables (level L) -------------------------------------------------------------------------------

// Per version 1..6: data codewords in total, error-correction codewords per block, number of equal-size blocks.
const VERSIONS = [
  null,
  { data: 19, ecc: 7, blocks: 1 },
  { data: 34, ecc: 10, blocks: 1 },
  { data: 55, ecc: 15, blocks: 1 },
  { data: 80, ecc: 20, blocks: 1 },
  { data: 108, ecc: 26, blocks: 1 },
  { data: 136, ecc: 18, blocks: 2 },
];
const MAX_VERSION = 6;
// Centre coordinate of the single alignment pattern (versions 2-6); it sits 7 modules from the bottom-right corner.
const alignmentCentre = (size) => size - 7;

// Bit capacity of the byte-mode header: 4 mode bits + 8 character-count bits (versions 1-9).
const HEADER_BITS = 12;

// ---- GF(256) arithmetic and Reed-Solomon -------------------------------------------------------------------

// Field generated by x^8 + x^4 + x^3 + x^2 + 1 (0x11D), the polynomial every QR code uses.
const GF_EXP = new Array(255);
const GF_LOG = new Array(256);
for (let i = 0, x = 1; i < 255; i++) {
  GF_EXP[i] = x;
  GF_LOG[x] = i;
  x <<= 1;
  if (x & 0x100) x ^= 0x11d;
}

function gfMul(a, b) {
  return a === 0 || b === 0 ? 0 : GF_EXP[(GF_LOG[a] + GF_LOG[b]) % 255];
}

// The generator polynomial (x - a^0)(x - a^1)...(x - a^(degree-1)), leading 1 omitted, highest power first.
function generatorPolynomial(degree) {
  const poly = new Array(degree).fill(0);
  poly[degree - 1] = 1;
  let root = 1;
  for (let i = 0; i < degree; i++) {
    for (let j = 0; j < degree; j++) {
      poly[j] = gfMul(poly[j], root);
      if (j + 1 < degree) poly[j] ^= poly[j + 1];
    }
    root = gfMul(root, 2);
  }
  return poly;
}

// Remainder of data(x) * x^degree divided by the generator: the error-correction codewords.
function reedSolomon(data, degree) {
  const gen = generatorPolynomial(degree);
  const rem = new Array(degree).fill(0);
  for (const byte of data) {
    const factor = byte ^ rem.shift();
    rem.push(0);
    for (let i = 0; i < degree; i++) rem[i] ^= gfMul(gen[i], factor);
  }
  return rem;
}

// ---- Text to codewords -------------------------------------------------------------------------------------

// UTF-8 by hand: TextEncoder is not among the globals shared/ may rely on. A lone surrogate becomes U+FFFD.
function utf8Bytes(text) {
  const bytes = [];
  for (const ch of text) {
    let cp = ch.codePointAt(0);
    if (cp >= 0xd800 && cp <= 0xdfff) cp = 0xfffd;
    if (cp < 0x80) bytes.push(cp);
    else if (cp < 0x800) bytes.push(0xc0 | (cp >> 6), 0x80 | (cp & 63));
    else if (cp < 0x10000) bytes.push(0xe0 | (cp >> 12), 0x80 | ((cp >> 6) & 63), 0x80 | (cp & 63));
    else bytes.push(0xf0 | (cp >> 18), 0x80 | ((cp >> 12) & 63), 0x80 | ((cp >> 6) & 63), 0x80 | (cp & 63));
  }
  return bytes;
}

function pickVersion(byteCount) {
  for (let v = 1; v <= MAX_VERSION; v++) {
    if (HEADER_BITS + byteCount * 8 <= VERSIONS[v].data * 8) return v;
  }
  return 0;
}

// Mode indicator, length, payload, terminator, padding to a whole codeword, then the alternating pad codewords 0xEC 0x11.
function dataCodewords(bytes, version) {
  const capacityBits = VERSIONS[version].data * 8;
  const bits = [];
  const push = (value, count) => {
    for (let i = count - 1; i >= 0; i--) bits.push((value >>> i) & 1);
  };
  push(0b0100, 4);
  push(bytes.length, 8);
  for (const b of bytes) push(b, 8);
  push(0, Math.min(4, capacityBits - bits.length));
  while (bits.length % 8) bits.push(0);
  const words = [];
  for (let i = 0; i < bits.length; i += 8) {
    let w = 0;
    for (let j = 0; j < 8; j++) w = (w << 1) | bits[i + j];
    words.push(w);
  }
  for (let pad = 0xec; words.length < VERSIONS[version].data; pad ^= 0xec ^ 0x11) words.push(pad);
  return words;
}

// Split into blocks, append each block's error correction, and interleave column by column as the standard requires.
function interleave(words, version) {
  const { data, ecc, blocks } = VERSIONS[version];
  const per = data / blocks;
  const dataBlocks = [];
  const eccBlocks = [];
  for (let b = 0; b < blocks; b++) {
    const block = words.slice(b * per, (b + 1) * per);
    dataBlocks.push(block);
    eccBlocks.push(reedSolomon(block, ecc));
  }
  const out = [];
  for (let i = 0; i < per; i++) for (const block of dataBlocks) out.push(block[i]);
  for (let i = 0; i < ecc; i++) for (const block of eccBlocks) out.push(block[i]);
  return out;
}

// ---- Matrix construction -----------------------------------------------------------------------------------

function makeGrid(size, fill) {
  return Array.from({ length: size }, () => new Array(size).fill(fill));
}

// Draws every fixed pattern into `dark` and records in `fixed` which modules are not data.
function drawFunctionPatterns(size, version) {
  const dark = makeGrid(size, false);
  const fixed = makeGrid(size, false);
  const put = (x, y, isDark) => {
    dark[y][x] = isDark;
    fixed[y][x] = true;
  };

  for (let i = 0; i < size; i++) {
    put(6, i, i % 2 === 0);   // vertical timing pattern
    put(i, 6, i % 2 === 0);   // horizontal timing pattern
  }

  // A finder pattern is a 7x7 target with a light separator ring around it (the ring may fall off the symbol).
  const finder = (cx, cy) => {
    for (let dy = -4; dy <= 4; dy++) {
      for (let dx = -4; dx <= 4; dx++) {
        const x = cx + dx;
        const y = cy + dy;
        if (x < 0 || y < 0 || x >= size || y >= size) continue;
        const ring = Math.max(Math.abs(dx), Math.abs(dy));
        put(x, y, ring !== 4 && ring !== 2);
      }
    }
  };
  finder(3, 3);
  finder(size - 4, 3);
  finder(3, size - 4);

  if (version >= 2) {
    const c = alignmentCentre(size);
    for (let dy = -2; dy <= 2; dy++) {
      for (let dx = -2; dx <= 2; dx++) put(c + dx, c + dy, Math.max(Math.abs(dx), Math.abs(dy)) !== 1);
    }
  }

  // Reserve the two format-information strips; the real bits are written once the mask is known.
  for (let i = 0; i < 9; i++) {
    fixed[8][i] = true;
    fixed[i][8] = true;
  }
  for (let i = 0; i < 8; i++) {
    fixed[8][size - 1 - i] = true;
    fixed[size - 1 - i][8] = true;
  }
  put(8, size - 8, true);   // the always-dark module
  return { dark, fixed };
}

// Places the codeword bits in the zig-zag order of the standard: two-module-wide columns from the right, alternating
// up and down, skipping the vertical timing column. Bits beyond the codewords (the remainder bits) stay light.
function placeData(dark, fixed, codewords) {
  const size = dark.length;
  let bit = 0;
  const total = codewords.length * 8;
  for (let right = size - 1; right >= 1; right -= 2) {
    if (right === 6) right = 5;
    const upward = ((size - 1 - right) >> 1) % 2 === 0;
    for (let step = 0; step < size; step++) {
      const y = upward ? size - 1 - step : step;
      for (let dx = 0; dx < 2; dx++) {
        const x = right - dx;
        if (fixed[y][x] || bit >= total) continue;
        dark[y][x] = ((codewords[bit >> 3] >>> (7 - (bit & 7))) & 1) === 1;
        bit++;
      }
    }
  }
}

const MASKS = [
  (x, y) => (x + y) % 2 === 0,
  (x, y) => y % 2 === 0,
  (x) => x % 3 === 0,
  (x, y) => (x + y) % 3 === 0,
  (x, y) => (Math.floor(x / 3) + (y >> 1)) % 2 === 0,
  (x, y) => ((x * y) % 2) + ((x * y) % 3) === 0,
  (x, y) => (((x * y) % 2) + ((x * y) % 3)) % 2 === 0,
  (x, y) => (((x + y) % 2) + ((x * y) % 3)) % 2 === 0,
];

// 15 format bits for level L (indicator 01) and a mask: 5 data bits, 10 BCH bits (generator 0x537), XOR 0x5412.
function formatBits(mask) {
  const data = (0b01 << 3) | mask;
  let rem = data << 10;
  for (let i = 4; i >= 0; i--) if ((rem >>> (i + 10)) & 1) rem ^= 0x537 << i;
  return ((data << 10) | rem) ^ 0x5412;
}

function writeFormat(dark, mask) {
  const size = dark.length;
  const bits = formatBits(mask);
  const bit = (i) => ((bits >>> i) & 1) === 1;
  for (let i = 0; i <= 5; i++) dark[i][8] = bit(i);
  dark[7][8] = bit(6);
  dark[8][8] = bit(7);
  dark[8][7] = bit(8);
  for (let i = 9; i < 15; i++) dark[8][14 - i] = bit(i);
  for (let i = 0; i < 8; i++) dark[8][size - 1 - i] = bit(i);
  for (let i = 8; i < 15; i++) dark[size - 15 + i][8] = bit(i);
}

// The four penalty rules of the standard (runs, 2x2 blocks, finder-like runs, dark/light balance); lowest total wins.
function penalty(dark) {
  const size = dark.length;
  let score = 0;

  for (const lines of [dark, dark[0].map((_, x) => dark.map((row) => row[x]))]) {
    for (const line of lines) {
      let run = 1;
      for (let i = 1; i <= size; i++) {
        if (i < size && line[i] === line[i - 1]) run++;
        else {
          if (run >= 5) score += run - 2;
          run = 1;
        }
      }
      for (let i = 0; i + 11 <= size; i++) {
        const span = line.slice(i, i + 11).map((m) => (m ? 1 : 0)).join('');
        if (span === '10111010000' || span === '00001011101') score += 40;
      }
    }
  }
  for (let y = 0; y + 1 < size; y++) {
    for (let x = 0; x + 1 < size; x++) {
      const c = dark[y][x];
      if (c === dark[y][x + 1] && c === dark[y + 1][x] && c === dark[y + 1][x + 1]) score += 3;
    }
  }
  let darkCount = 0;
  for (const row of dark) for (const m of row) if (m) darkCount++;
  score += Math.floor(Math.abs(darkCount * 20 - size * size * 10) / (size * size)) * 10;
  return score;
}

/**
 * Encodes `text` (as UTF-8) into a QR Code symbol.
 * @param {string} text
 * @returns {boolean[][] | null} rows of modules (true = dark) without a quiet zone, or null when the text is not a
 *   string or does not fit version 6-L (QR_MAX_BYTES bytes).
 */
export function qrMatrix(text) {
  if (typeof text !== 'string') return null;
  const bytes = utf8Bytes(text);
  const version = pickVersion(bytes.length);
  if (!version) return null;

  const size = 17 + 4 * version;
  const codewords = interleave(dataCodewords(bytes, version), version);
  const { dark: base, fixed } = drawFunctionPatterns(size, version);
  placeData(base, fixed, codewords);

  let best = null;
  let bestScore = Infinity;
  for (let mask = 0; mask < MASKS.length; mask++) {
    const candidate = base.map((row) => row.slice());
    for (let y = 0; y < size; y++) {
      for (let x = 0; x < size; x++) if (!fixed[y][x] && MASKS[mask](x, y)) candidate[y][x] = !candidate[y][x];
    }
    writeFormat(candidate, mask);
    const score = penalty(candidate);
    if (score < bestScore) {
      best = candidate;
      bestScore = score;
    }
  }
  return best;
}
